initial commit
Signed-off-by: Hamed Faramarzi <hamed.faramarzi@gmail.com>

diff --git a/bin/pkrenv b/bin/pkrenv
--- a/bin/pkrenv
+++ b/bin/pkrenv
@@ -10,47 +10,47 @@ function early_death() {
   exit 1;
 };
 
-if [ -z "${TFENV_ROOT:-""}" ]; then
+if [ -z "${PKRENV_ROOT:-""}" ]; then
   # http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
   readlink_f() {
     local target_file="${1}";
     local file_name;
 
     while [ "${target_file}" != "" ]; do
-      cd "${target_file%/*}" || early_death "Failed to 'cd \$(${target_file%/*})' while trying to determine TFENV_ROOT";
-      file_name="${target_file##*/}" || early_death "Failed to '\"${target_file##*/}\"' while trying to determine TFENV_ROOT";
+      cd "${target_file%/*}" || early_death "Failed to 'cd \$(${target_file%/*})' while trying to determine PKRENV_ROOT";
+      file_name="${target_file##*/}" || early_death "Failed to '\"${target_file##*/}\"' while trying to determine PKRENV_ROOT";
       target_file="$(readlink "${file_name}")";
     done;
 
     echo "$(pwd -P)/${file_name}";
   };
-  TFENV_SHIM=$(readlink_f "${0}")
-  TFENV_ROOT="${TFENV_SHIM%/*/*}";
-  [ -n "${TFENV_ROOT}" ] || early_death "Failed to determine TFENV_ROOT";
+  PKRENV_SHIM=$(readlink_f "${0}")
+  PKRENV_ROOT="${PKRENV_SHIM%/*/*}";
+  [ -n "${PKRENV_ROOT}" ] || early_death "Failed to determine PKRENV_ROOT";
 
 else
-  TFENV_ROOT="${TFENV_ROOT%/}";
+  PKRENV_ROOT="${PKRENV_ROOT%/}";
 fi;
-export TFENV_ROOT;
+export PKRENV_ROOT;
 
-if [ -n "${TFENV_HELPERS:-""}" ]; then
-  log 'debug' 'TFENV_HELPERS is set, not sourcing helpers again';
+if [ -n "${PKRENV_HELPERS:-""}" ]; then
+  log 'debug' 'PKRENV_HELPERS is set, not sourcing helpers again';
 else
-  [ "${TFENV_DEBUG:-0}" -gt 0 ] && >&2 echo "[DEBUG] Sourcing helpers from ${TFENV_ROOT}/lib/helpers.sh";
-  if source "${TFENV_ROOT}/lib/helpers.sh"; then
+  [ "${PKRENV_DEBUG:-0}" -gt 0 ] && >&2 echo "[DEBUG] Sourcing helpers from ${PKRENV_ROOT}/lib/helpers.sh";
+  if source "${PKRENV_ROOT}/lib/helpers.sh"; then
     log 'debug' 'Helpers sourced successfully';
   else
-    early_death "Failed to source helpers from ${TFENV_ROOT}/lib/helpers.sh";
+    early_death "Failed to source helpers from ${PKRENV_ROOT}/lib/helpers.sh";
   fi;
 fi;
 
 # Ensure libexec and bin are in $PATH
 for dir in libexec bin; do
   case ":${PATH}:" in
-    *:${TFENV_ROOT}/${dir}:*) log 'debug' "\$PATH already contains '${TFENV_ROOT}/${dir}', not adding it again";;
+    *:${PKRENV_ROOT}/${dir}:*) log 'debug' "\$PATH already contains '${PKRENV_ROOT}/${dir}', not adding it again";;
     *)
-      log 'debug' "\$PATH does not contain '${TFENV_ROOT}/${dir}', prepending and exporting it now";
-      export PATH="${TFENV_ROOT}/${dir}:${PATH}";
+      log 'debug' "\$PATH does not contain '${PKRENV_ROOT}/${dir}', prepending and exporting it now";
+      export PATH="${PKRENV_ROOT}/${dir}:${PATH}";
       ;;
   esac;
 done;
@@ -61,8 +61,8 @@ done;
 
 declare arg="${1:-""}";
 
-log 'debug' "Setting TFENV_DIR to ${PWD}";
-export TFENV_DIR="${PWD}";
+log 'debug' "Setting PKRENV_DIR to ${PWD}";
+export PKRENV_DIR="${PWD}";
 
 abort() {
   log 'debug' 'Aborting...';
@@ -70,38 +70,38 @@ abort() {
     if [ "${#}" -eq 0 ]; then
       cat -;
     else
-      echo "tfenv: ${*}";
+      echo "pkrenv: ${*}";
     fi;
   } >&2;
 };
 
-log 'debug' "tfenv argument is: ${arg}";
+log 'debug' "pkrenv argument is: ${arg}";
 
 case "${arg}" in
   "")
     log 'debug' 'No argument provided, dumping version and help and aborting';
     {
-      tfenv---version;
-      tfenv-help;
+      pkrenv---version;
+      pkrenv-help;
     } | abort && exit 1;
 exit 1;
     ;;
   -v | --version )
-    log 'debug' 'tfenv version requested...';
-    exec tfenv---version;
+    log 'debug' 'pkrenv version requested...';
+    exec pkrenv---version;
     ;;
   -h | --help )
-    log 'debug' 'tfenv help requested...';
-    exec tfenv-help;
+    log 'debug' 'pkrenv help requested...';
+    exec pkrenv-help;
     ;;
   *)
     log 'debug' "Long argument provided: ${arg}";
-    command_path="$(command -v "tfenv-${arg}" || true)";
+    command_path="$(command -v "pkrenv-${arg}" || true)";
     log 'debug' "Resulting command-path: ${command_path}";
     if [ -z "${command_path}" ]; then
       {
         echo "No such command '${arg}'";
-        tfenv-help;
+        pkrenv-help;
       } | abort && exit 1;
     fi;
     shift 1;
diff --git a/libexec/pkrenv-pin b/libexec/pkrenv-pin
--- a/libexec/pkrenv-pin
+++ b/libexec/pkrenv-pin
@@ -27,7 +27,7 @@ if [ -z "${PKRENV_ROOT:-""}" ]; then
   };
 
   PKRENV_ROOT="$(cd "$(dirname "$(readlink_f "${0}")")/.." && pwd)";
-  [ -n ${PKRENV_ROOT} ] || early_death "Failed to 'cd \"\$(dirname \"\$(readlink_f \"${0}\")\")/..\" && pwd' while trying to determine PKRENV_ROOT";
+  [ -n "${PKRENV_ROOT}" ] || early_death "Failed to 'cd \"\$(dirname \"\$(readlink_f \"${0}\")\")/..\" && pwd' while trying to determine PKRENV_ROOT";
 else
   PKRENV_ROOT="${PKRENV_ROOT%/}";
 fi;
@@ -44,40 +44,34 @@ else
   fi;
 fi;
 
+# Ensure libexec and bin are in $PATH
+for dir in libexec bin; do
+  case ":${PATH}:" in
+    *:${PKRENV_ROOT}/${dir}:*) log 'debug' "\$PATH already contains '${PKRENV_ROOT}/${dir}', not adding it again";;
+    *)
+      log 'debug' "\$PATH does not contain '${PKRENV_ROOT}/${dir}', prepending and exporting it now";
+      export PATH="${PKRENV_ROOT}/${dir}:${PATH}";
+      ;;
+  esac;
+done;
+
 #####################
 # Begin Script Body #
 #####################
 
-declare -a errors=();
+[ "${#}" -ne 0 ] \
+  && log 'error' "usage: pkrenv pin";
 
-log 'info' '### Testing symlink functionality';
+[ -d "${PKRENV_CONFIG_DIR}/versions/" ] \
+  || log 'error' 'No versions available. Please install one with: pkrenv install';
 
-PKRENV_BIN_DIR='/tmp/pkrenv-test';
-log 'info' "## Creating/clearing ${PKRENV_BIN_DIR}"
-rm -rf "${PKRENV_BIN_DIR}" && mkdir "${PKRENV_BIN_DIR}";
-log 'info' "## Symlinking ${PWD}/bin/* into ${PKRENV_BIN_DIR}";
-ln -s "${PWD}"/bin/* "${PKRENV_BIN_DIR}";
+[[ -x "${PKRENV_CONFIG_DIR}/versions" && -r "${PKRENV_CONFIG_DIR}/versions" ]] \
+  || log 'error' "pkrenv versions directory is inaccessible: ${PKRENV_CONFIG_DIR}/versions";
 
-cleanup || log 'error' 'Cleanup failed?!';
+version_name="$(pkrenv-version-name 2>/dev/null || true)" \
+  && log 'debug' "pkrenv-version-name reported: ${version_name}";
 
-log 'info' '## Installing 0.8.2';
-${PKRENV_BIN_DIR}/pkrenv install 0.8.2 || error_and_proceed 'Install failed';
-
-log 'info' '## Using 0.8.2';
-${PKRENV_BIN_DIR}/pkrenv use 0.8.2 || error_and_proceed 'Use failed';
-
-log 'info' '## Check-Version for 0.8.2';
-check_active_version 0.8.2 || error_and_proceed 'Version check failed';
-
-if [ "${#errors[@]}" -gt 0 ]; then
-  log 'warn' '===== The following symlink tests failed =====';
-  for error in "${errors[@]}"; do
-    log 'warn' "\t${error}";
-  done;
-  log 'error' 'Symlink test failure(s)';
-  exit 1;
-else
-  log 'info' 'All symlink tests passed.';
-fi;
+echo "${version_name}" > .packer-version;
+log 'info' "Pinned version by writing \"${version_name}\" to $(pwd)/.packer-version";
 
 exit 0;
